import LoginCard from "@/components/auth/LoginCard";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Login - Ping Service",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="min-h-screen flex items-center justify-center">
      <LoginCard />
    </div>
  );
}
