import SignupCard from "@/components/auth/SignupCard";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Signup - Ping Service",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <div className="min-h-screen flex items-center justify-center">
      <SignupCard />
    </div>
  );
}
